baseURL="http://mangakuma.net/"
languageCode = "en-us"
title = "MangaKuma"
theme = "mangakuma"
paginate = 30
enableEmoji = true

[taxonomies]
  category = "categories"
  tag = "tags"
  
[related]

# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 150
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"